backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "temata"
    label: "Témata"
    folder: "temata"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "hlavni" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "temata" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subitle", name: "subtitle", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false, }
      - { label: "Body", name: "body", widget: "markdown" }
